POSTGRES_USER: postgres
POSTGRES_PASSWORD: "998915309764"
POSTGRES_DB: urgut_clothing_development
TELEGRAM_TOKEN: 6319741438:AAFOj3A4Gob0hCFWowtBJfaL14d8DbAZaxcTEST
TELEGRAM_CHAT_ID: -4004645147TEST
HOST_URL: http://localhost:3000
TELEGRAM_WARNING_CHAT_ID: -4031454161
RAILS_BUILD: false
HOST_URL: web-production-b7ee.up.railway.app
